### ISSUE TITLE
Failing to start on LInux, latest-linux.yml missing

### ISSUE THREAD

**Issue by arthurzenika** [getgridea/gridea#1145]
```
Checking for update
instance sftp deploy
Main process runing... /home/arthur/Documents/Gridea
(node:302853) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:302853) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
Preview server is running on port : 4000
Error: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/getgridea/gridea/releases/download/v0.9.3/latest-linux.yml): HttpError: 404 
"method: GET url: https://github.com/getgridea/gridea/releases/download/v0.9.3/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "status": "404",
  "server": "GitHub.com",
  "date": "Wed, 20 Sep 2023 11:42:31 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "BF6A:7180:353BF5C:35F734A:650ADAA7"
}
    at d (/tmp/.mount_GrideaaEn0qX/resources/app/background.js:2:650716)
    at a.ElectronHttpExecutor.handleResponse (/tmp/.mount_GrideaaEn0qX/resources/app/background.js:2:652343)
    at ClientRequest.<anonymous> (/tmp/.mount_GrideaaEn0qX/resources/app/background.js:2:651812)
    at ClientRequest.emit (events.js:203:13)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2569:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:131:23)
    at a.newError (/tmp/.mount_GrideaaEn0qX/resources/app/background.js:2:95740)
    at a.GitHubProvider.getLatestVersion (/tmp/.mount_GrideaaEn0qX/resources/app/background.js:2:822373)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/getgridea/gridea/releases/download/v0.9.3/latest-linux.yml): HttpError: 404 
"method: GET url: https://github.com/getgridea/gridea/releases/download/v0.9.3/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "status": "404",
  "server": "GitHub.com",
  "date": "Wed, 20 Sep 2023 11:42:31 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "BF6A:7180:353BF5C:35F734A:650ADAA7"
}
    at d (/tmp/.mount_GrideaaEn0qX/resources/app/background.js:2:650716)
    at a.ElectronHttpExecutor.handleResponse (/tmp/.mount_GrideaaEn0qX/resources/app/background.js:2:652343)
    at ClientRequest.<anonymous> (/tmp/.mount_GrideaaEn0qX/resources/app/background.js:2:651812)
    at ClientRequest.emit (events.js:203:13)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2569:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:131:23)
    at a.newError (/tmp/.mount_GrideaaEn0qX/resources/app/background.js:2:95740)
    at a.GitHubProvider.getLatestVersion (/tmp/.mount_GrideaaEn0qX/resources/app/background.js:2:822373)
[302853:0920/134232.264769:FATAL:gpu_data_manager_impl_private.cc(986)] The display compositor is frequently crashing. Goodbye.
Failed to generate minidump.fish: Job 1, '~/Downloads/Gridea-0.9.3.AppIma…' terminated by signal SIGILL (Illegal instruction)


```
(sorry, I don't speak chinese so I can't follow the template)

**Comment by arthurzenika** [comment]
Starting with `--no-sandbox` works, but I guess the missing latest-linux.yml in the Releases is still a problem.
