### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by huopochuan** [getgridea/gridea#368]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |     maos |
| 软件版本 | v0.8.3      |
| 主题名称 |    Fly  |

---

## 当前行为

Uncaught Exception:
RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 65536.
    at Server.listen (net.js:1353:13)
    at Function.b.listen (/Applications/Gridea.app/Contents/Resources/app/background.js:374:4546)
    at i (/Applications/Gridea.app/Contents/Resources/app/background.js:554:809562)
    at Server.<anonymous> (/Applications/Gridea.app/Contents/Resources/app/background.js:554:809676)
    at Server.emit (events.js:200:13)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1410:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:17)

**Comment by huopochuan** [comment]
已经卸载了。。。

**Comment by EryouHao** [comment]
sorry 听到这个消息，不知道使用最新版本是否可用？

**Comment by huopochuan** [comment]
之前写了一大片文章，保存后都丢失了。之后就没在用了。不过这个软件很不错。

**Comment by EryouHao** [comment]
🙏
